# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 198e3bb6a494e5003244cee1bcd9454f26a65dabb8afbbf123fef0c1826b43713a7ff78af60914c16505aab7dfb0edc33514fbdfb75f5265fd97e88529990cf9

test:
  secret_key_base: 8fc70b720849f78b24585e78e72010b13704642763b8ec264f12ab3454d0abe40ca603cf7dcea019e5d6afab7709db56fe92249d182195df6ef895d9142e93da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
